import Extraction.Funs
import Extraction.Types
import Aeneas

/-!
# Aeneas extraction — library root

Imports the Aeneas-generated definitions (`Extraction.Funs`,
`Extraction.Types`) and the Aeneas backend itself. The hand-written
refinement proof modules (`U32`, `ToU32s`, `Compress`, `RoundStep`,
`Loop0`, `Loop1`, `FinalBlock`, `SetChain`, `Sha256`, `Spec`,
`AxiomCheck`) live alongside this file at the lake-package root and
import it.

The `Extraction.Funs` / `Extraction.Types` modules under `Extraction/`
are regenerated by the Aeneas extraction pipeline; do not hand-edit
them. The inner Lean namespace remains `sha2` to match the Rust crate.
-/
