name: sha2-fv

on:
  pull_request:
    paths:
      - ".github/workflows/sha2.yml"
      - "sha2/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: sha2

env:
  RUSTFLAGS: -Dwarnings
  CARGO_INCREMENTAL: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.85.0
          - stable
        features:
          - --no-default-features --features sha256
          - --no-default-features --features sha512
          - --all-features
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build ${{ matrix.features }}
      - run: cargo test ${{ matrix.features }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check
